name: main
on:
  push:
    branches:
      
main
jobs:
  test-and-check:
    runs-on: ${{ matrix.os }}
#pobieramy dane z sekcji os
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, 3.10, 3.11]
        exclude: 
          
os: ubuntu-latest
          python-version: "3.9"
#wypisujemy systemy os oraz wersje pythona
    steps:
      
name: instalacja Pythona
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
#pobieramy dane z sekcji python-version
      
name: update pipa
      run: |
        python -m pip install --upgrade pip

      
name: pobieramy flake8 oraz unittest
      run: |
        python -m pip install flake8
        python -m pip install unittest
name: Wyświetlamy wersje Pythona
    run: |
      python --version
name: używamy flake8
  run: |
    flake8
name: używamy unittest
run: |
  python -m unittest discover -v
