name: Check Python Version and Syntax

on:
  push:
    branches:
      - main

jobs:
  check-python-version:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Display Python Version
      run: |
        python --version

  check-syntax:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps: 
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install flake8
      run: |
        python -m pip install flake8

    - name: Display Python Version
      run: |
        python --version

    - name: Run Flake8
      run: |
        flake8
